import type { Metadata } from "next";
import { ClerkProvider, Show, UserButton } from "@clerk/nextjs";
import ConvexClientProvider from "@/app/components/ConvexClientProvider";
import { gelasioSans, geistMono, italianno } from "./fonts";
import "./globals.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", gelasioSans.variable, geistMono.variable, italianno.variable, "font-sans", "dark")}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          <ConvexClientProvider>
            <header className="fixed top-0 right-0 z-50 flex items-center gap-3 p-4">
              <Show when="signed-in">
                <UserButton />
              </Show>
            </header>
            {children}
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
